version: '3.9'

services:
  app:
    build:
      context: ./app
    container_name: python-app
    depends_on:
      - llm
    networks:
      - llm-net

  llm:
    build:
      context: ./model
    container_name: llm-model
    ports:
      - "8000:8000"
    networks:
      - llm-net

networks:
  llm-net:
    driver: bridge
